FROM mysql:8.0.31

# COPY ./sql/ /docker-entrypoint-initdb.d/

#CMD ["mysqld"]

# docker build -t mysql-img .

# docker run --name db_mysql -p 3306:3306 -d mysql-img

# docker exec -it db_mysql /bin/bash

# docker mysql -u root -p
